### ISSUE TITLE
findByCreditCode

### ISSUE THREAD

**Issue by gustavoacbrito** [cami-la/credit-application-system#12]
Estou recebendo dois erros quando tento implementar a função findByCreditCode no CreditService
minha função está exatamente igual implementado na aula.
`override fun findByCreditCode(customerId: Long,creditCode: UUID): Credit? {
        val credit: Credit = (this.creditRepository.findByCreditCode(creditCode)
            ?: throw RuntimeException("Credit code $creditCode not found"))
        if (credit.customer?.id == customerId){
            return credit
        } else {
            throw RuntimeException("Contact admin")
        }
    }`
    CreditRepositoy da mesma maneira: 
`package me.dio.creditapplicationsystem.repository
import me.dio.creditapplicationsystem.entity.Credit
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository
import java.util.UUID
@Repository
interface CreditRepository: JpaRepository<Credit,Long>{
    fun findByCreditCode(creditCode: UUID) : Credit?
}`

porém recebo esses erros:
Class 'CreditService' is not abstract and does not implement abstract member public abstract fun findByCreditCode(creditCode: UUID): Credit defined in me.dio.creditapplicationsystem.service.ICreditService
'findByCreditCode' overrides nothing

Não estou conseguindo identificar oq pode ser a causa.

**Comment by gustavoacbrito** [comment]
Problema estava em ICreditService. Resolvido

**Comment by cami-la** [comment]
Fico feliz que tenha resolvido! Caso apresente outra dúvida, fico à disposição. (:
