### ISSUE TITLE
Ajuda com uma ideia

### ISSUE THREAD

**Issue by analuizagn** [cami-la/credit-application-system#35]
Queria fazer um formulário HTML que faça a mesma função do Postman de lançar dados no Banco, pesquisei algumas formas de fazer, mas, nenhuma funcionou. Teria alguma forma de fazer?

**Comment by cami-la** [comment]
Oi, @analuizagn. Tudo certinho?

Para integrar nosso formulário HTML com a API Spring em Kotlin, você pode usar JavaScript para enviar os dados do formulário para a API. Recomendo o uso de bibliotecas como Fetch API ou Axios para simplificar o processo.

Inclusive, considerando a complexidade, você pode optar por frameworks como Vue, React ou Angular, que facilitam o desenvolvimento de SPAs e a comunicação com APIs.

**Comment by analuizagn** [comment]
Ok, muito obrigada pelas dicas!
